image_location config items.
arceos-hypervisor/axvm pull request #3
Opened 2024-10-15 04:09 UTC by luodeb

2024-10-15 08:31 UTC, hky1999 requested changes
what happened to ci

2024-10-15 09:05 UTC, luodeb commented
> what happened to ci

Rust nightly fails to build it, 
https://github.com/rust-lang/rust/issues/131602

Fix it by modifying the `asm!` to `core::arch::naked_asm!`.

2024-10-17 10:58 UTC, hky1999 commented
> > what happened to ci
> 
> Rust nightly fails to build it, [rust-lang/rust#131602](https://github.com/rust-lang/rust/issues/131602)
> 
> Fix it by modifying the `asm!` to `core::arch::naked_asm!`.

rename to the newest main branch please, which fixed this ci problem.

this `naked_asm` problem has been found in ArceOS before, we just ignore it through fixed-version of rust toolchain.

you can refer to https://github.com/arceos-hypervisor/axvm/pull/4/commits/ddb72aa0f211f47ed192991cff083cbd645086d1 for details

2024-10-18 05:44 UTC, buhenxihuan approved these changes

2024-10-18 05:45 UTC, hky1999 approved these changes

2024-10-18 05:48 UTC, merged